### PR TITLE
Little layout edits

### PR DESCRIPTION
**Pull request by harikautilya**

### CODE REVIEW

**Comment by ashishkumar160** [comment]
Hey @harikautilya ,
You did fix the problem of overlapping, but can't we do it using ConstraintLayout? I see you have used LinearLayout instead.

**Comment by harikautilya** [comment]
yes u can do .....just go to design and right click on the view and set convert to Constraint layout

**Comment by harikautilya** [comment]
Also i suggest you  use constraint layout only for a full page static content only

**Comment by ashishkumar160** [comment]
So in this case Linear Layout is much better?

**Comment by harikautilya** [comment]
Yes

**Pull request merged**
